// Mock Data for Pharmacy Inventory System
// Hospital Pharmacy Management - Sample Data

import {
  Medication,
  Patient,
  Prescription,
  StockAlert,
  InventoryTransaction,
  Physician,
  DashboardStats,
} from "./types";

export const mockMedications: Medication[] = [
  {
    id: "MED-001",
    name: "Amoxicillin 500mg",
    genericName: "Amoxicillin",
    brandName: "Amoxil",
    category: "Antibiotics",
    form: "Capsule",
    strength: "500mg",
    unit: "capsule",
    batchNumber: "BTH-2024-001",
    lotNumber: "LOT-A1234",
    quantity: 2500,
    minStockLevel: 500,
    maxStockLevel: 5000,
    reorderPoint: 750,
    expirationDate: "2026-03-15",
    manufacturer: "Pfizer Inc.",
    supplier: "MedSupply Thailand",
    unitPrice: 2.5,
    location: "Shelf A-1",
    barcode: "5901234123457",
    ndcCode: "0005-5454-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (20-25°C)",
    contraindications: ["Penicillin allergy", "Mononucleosis"],
    sideEffects: ["Nausea", "Diarrhea", "Rash"],
    interactions: ["Methotrexate", "Warfarin"],
    lastRestocked: "2024-11-15",
    createdAt: "2024-01-15",
    updatedAt: "2024-11-15",
  },
  {
    id: "MED-002",
    name: "Metformin 850mg",
    genericName: "Metformin Hydrochloride",
    brandName: "Glucophage",
    category: "Diabetes",
    form: "Tablet",
    strength: "850mg",
    unit: "tablet",
    batchNumber: "BTH-2024-002",
    lotNumber: "LOT-M5678",
    quantity: 180,
    minStockLevel: 300,
    maxStockLevel: 3000,
    reorderPoint: 500,
    expirationDate: "2025-08-20",
    manufacturer: "Bristol-Myers Squibb",
    supplier: "PharmaDist Co.",
    unitPrice: 1.8,
    location: "Shelf B-3",
    barcode: "5901234123458",
    ndcCode: "0005-5455-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (15-30°C)",
    contraindications: ["Renal impairment", "Metabolic acidosis"],
    sideEffects: ["GI upset", "Lactic acidosis (rare)"],
    interactions: ["Contrast dye", "Alcohol"],
    lastRestocked: "2024-10-20",
    createdAt: "2024-02-10",
    updatedAt: "2024-10-20",
  },
  {
    id: "MED-003",
    name: "Morphine Sulfate 10mg",
    genericName: "Morphine Sulfate",
    brandName: "MS Contin",
    category: "Analgesics",
    form: "Tablet",
    strength: "10mg",
    unit: "tablet",
    batchNumber: "BTH-2024-003",
    lotNumber: "LOT-MS789",
    quantity: 50,
    minStockLevel: 100,
    maxStockLevel: 500,
    reorderPoint: 150,
    expirationDate: "2025-12-31",
    manufacturer: "Purdue Pharma",
    supplier: "Controlled Med Supply",
    unitPrice: 15.0,
    location: "Secure Cabinet SC-1",
    barcode: "5901234123459",
    ndcCode: "0005-5456-04",
    controlledSubstance: true,
    scheduleClass: "II",
    requiresRefrigeration: false,
    storageConditions: "Store in secure location at room temperature",
    contraindications: ["Respiratory depression", "MAO inhibitors"],
    sideEffects: ["Constipation", "Sedation", "Respiratory depression"],
    interactions: ["CNS depressants", "MAOIs"],
    lastRestocked: "2024-11-01",
    createdAt: "2024-01-20",
    updatedAt: "2024-11-01",
  },
  {
    id: "MED-004",
    name: "Lisinopril 10mg",
    genericName: "Lisinopril",
    brandName: "Zestril",
    category: "Cardiovascular",
    form: "Tablet",
    strength: "10mg",
    unit: "tablet",
    batchNumber: "BTH-2024-004",
    lotNumber: "LOT-L2345",
    quantity: 1800,
    minStockLevel: 400,
    maxStockLevel: 4000,
    reorderPoint: 600,
    expirationDate: "2026-06-30",
    manufacturer: "AstraZeneca",
    supplier: "MedSupply Thailand",
    unitPrice: 3.2,
    location: "Shelf C-2",
    barcode: "5901234123460",
    ndcCode: "0005-5457-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature, protect from moisture",
    contraindications: ["Pregnancy", "Angioedema history"],
    sideEffects: ["Cough", "Dizziness", "Hyperkalemia"],
    interactions: ["Potassium supplements", "NSAIDs"],
    lastRestocked: "2024-11-10",
    createdAt: "2024-03-05",
    updatedAt: "2024-11-10",
  },
  {
    id: "MED-005",
    name: "Insulin Glargine 100U/mL",
    genericName: "Insulin Glargine",
    brandName: "Lantus",
    category: "Diabetes",
    form: "Injection",
    strength: "100U/mL",
    unit: "vial",
    batchNumber: "BTH-2024-005",
    lotNumber: "LOT-IG567",
    quantity: 75,
    minStockLevel: 50,
    maxStockLevel: 200,
    reorderPoint: 80,
    expirationDate: "2025-02-28",
    manufacturer: "Sanofi",
    supplier: "BioPharma Supply",
    unitPrice: 85.0,
    location: "Refrigerator R-1",
    barcode: "5901234123461",
    ndcCode: "0005-5458-04",
    controlledSubstance: false,
    requiresRefrigeration: true,
    storageConditions: "Refrigerate (2-8°C), do not freeze",
    contraindications: ["Hypoglycemia", "Insulin allergy"],
    sideEffects: ["Hypoglycemia", "Injection site reactions"],
    interactions: ["Beta-blockers", "ACE inhibitors"],
    lastRestocked: "2024-11-20",
    createdAt: "2024-04-12",
    updatedAt: "2024-11-20",
  },
  {
    id: "MED-006",
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    brandName: "Prilosec",
    category: "Gastrointestinal",
    form: "Capsule",
    strength: "20mg",
    unit: "capsule",
    batchNumber: "BTH-2024-006",
    lotNumber: "LOT-O8901",
    quantity: 3200,
    minStockLevel: 600,
    maxStockLevel: 6000,
    reorderPoint: 900,
    expirationDate: "2026-09-15",
    manufacturer: "AstraZeneca",
    supplier: "MedSupply Thailand",
    unitPrice: 2.1,
    location: "Shelf A-4",
    barcode: "5901234123462",
    ndcCode: "0005-5459-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (15-25°C)",
    contraindications: ["Rilpivirine use"],
    sideEffects: ["Headache", "Abdominal pain", "Diarrhea"],
    interactions: ["Clopidogrel", "Methotrexate"],
    lastRestocked: "2024-11-18",
    createdAt: "2024-02-28",
    updatedAt: "2024-11-18",
  },
  {
    id: "MED-007",
    name: "Albuterol Sulfate 90mcg/actuation",
    genericName: "Albuterol Sulfate",
    brandName: "ProAir HFA",
    category: "Respiratory",
    form: "Inhaler",
    strength: "90mcg/actuation",
    unit: "inhaler",
    batchNumber: "BTH-2024-007",
    lotNumber: "LOT-AS234",
    quantity: 45,
    minStockLevel: 100,
    maxStockLevel: 500,
    reorderPoint: 150,
    expirationDate: "2025-04-30",
    manufacturer: "Teva Pharmaceuticals",
    supplier: "Respiratory Med Supply",
    unitPrice: 28.5,
    location: "Shelf D-1",
    barcode: "5901234123463",
    ndcCode: "0005-5460-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (15-25°C)",
    contraindications: ["Hypersensitivity to albuterol"],
    sideEffects: ["Tremor", "Tachycardia", "Nervousness"],
    interactions: ["Beta-blockers", "MAOIs"],
    lastRestocked: "2024-10-15",
    createdAt: "2024-05-20",
    updatedAt: "2024-10-15",
  },
  {
    id: "MED-008",
    name: "Atorvastatin 20mg",
    genericName: "Atorvastatin Calcium",
    brandName: "Lipitor",
    category: "Cardiovascular",
    form: "Tablet",
    strength: "20mg",
    unit: "tablet",
    batchNumber: "BTH-2024-008",
    lotNumber: "LOT-AT567",
    quantity: 2100,
    minStockLevel: 500,
    maxStockLevel: 5000,
    reorderPoint: 750,
    expirationDate: "2026-11-30",
    manufacturer: "Pfizer Inc.",
    supplier: "CardioMed Supply",
    unitPrice: 4.5,
    location: "Shelf C-1",
    barcode: "5901234123464",
    ndcCode: "0005-5461-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (20-25°C)",
    contraindications: ["Active liver disease", "Pregnancy"],
    sideEffects: ["Muscle pain", "Liver enzyme elevation"],
    interactions: ["Grapefruit juice", "Gemfibrozil"],
    lastRestocked: "2024-11-12",
    createdAt: "2024-03-15",
    updatedAt: "2024-11-12",
  },
  {
    id: "MED-009",
    name: "Sertraline 50mg",
    genericName: "Sertraline Hydrochloride",
    brandName: "Zoloft",
    category: "Psychiatric",
    form: "Tablet",
    strength: "50mg",
    unit: "tablet",
    batchNumber: "BTH-2024-009",
    lotNumber: "LOT-SR890",
    quantity: 890,
    minStockLevel: 300,
    maxStockLevel: 2000,
    reorderPoint: 450,
    expirationDate: "2026-07-20",
    manufacturer: "Pfizer Inc.",
    supplier: "PsychMed Supply",
    unitPrice: 2.8,
    location: "Shelf E-2",
    barcode: "5901234123465",
    ndcCode: "0005-5462-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (15-30°C)",
    contraindications: ["MAO inhibitors", "Pimozide use"],
    sideEffects: ["Nausea", "Insomnia", "Dizziness"],
    interactions: ["MAOIs", "SSRIs", "Triptans"],
    lastRestocked: "2024-11-05",
    createdAt: "2024-04-22",
    updatedAt: "2024-11-05",
  },
  {
    id: "MED-010",
    name: "Prednisone 10mg",
    genericName: "Prednisone",
    brandName: "Deltasone",
    category: "Immunosuppressants",
    form: "Tablet",
    strength: "10mg",
    unit: "tablet",
    batchNumber: "BTH-2024-010",
    lotNumber: "LOT-PR123",
    quantity: 1500,
    minStockLevel: 400,
    maxStockLevel: 3000,
    reorderPoint: 600,
    expirationDate: "2026-05-15",
    manufacturer: "Merck & Co.",
    supplier: "MedSupply Thailand",
    unitPrice: 1.5,
    location: "Shelf B-2",
    barcode: "5901234123466",
    ndcCode: "0005-5463-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (20-25°C)",
    contraindications: ["Systemic fungal infections"],
    sideEffects: ["Weight gain", "Mood changes", "Hyperglycemia"],
    interactions: ["NSAIDs", "Live vaccines"],
    lastRestocked: "2024-10-28",
    createdAt: "2024-02-18",
    updatedAt: "2024-10-28",
  },
  {
    id: "MED-011",
    name: "Epinephrine 1mg/mL",
    genericName: "Epinephrine",
    brandName: "Adrenalin",
    category: "Emergency",
    form: "Injection",
    strength: "1mg/mL",
    unit: "ampule",
    batchNumber: "BTH-2024-011",
    lotNumber: "LOT-EP456",
    quantity: 120,
    minStockLevel: 50,
    maxStockLevel: 300,
    reorderPoint: 80,
    expirationDate: "2025-01-15",
    manufacturer: "Par Pharmaceuticals",
    supplier: "Emergency Med Supply",
    unitPrice: 12.0,
    location: "Emergency Cart EC-1",
    barcode: "5901234123467",
    ndcCode: "0005-5464-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Protect from light, store at room temperature",
    contraindications: ["None in emergency situations"],
    sideEffects: ["Tachycardia", "Anxiety", "Tremor"],
    interactions: ["Beta-blockers", "MAOIs"],
    lastRestocked: "2024-11-22",
    createdAt: "2024-06-10",
    updatedAt: "2024-11-22",
  },
  {
    id: "MED-012",
    name: "Diazepam 5mg",
    genericName: "Diazepam",
    brandName: "Valium",
    category: "Psychiatric",
    form: "Tablet",
    strength: "5mg",
    unit: "tablet",
    batchNumber: "BTH-2024-012",
    lotNumber: "LOT-DZ789",
    quantity: 25,
    minStockLevel: 50,
    maxStockLevel: 200,
    reorderPoint: 75,
    expirationDate: "2025-10-20",
    manufacturer: "Roche",
    supplier: "Controlled Med Supply",
    unitPrice: 8.5,
    location: "Secure Cabinet SC-2",
    barcode: "5901234123468",
    ndcCode: "0005-5465-04",
    controlledSubstance: true,
    scheduleClass: "IV",
    requiresRefrigeration: false,
    storageConditions: "Store in secure location at room temperature",
    contraindications: ["Severe respiratory depression", "Sleep apnea"],
    sideEffects: ["Sedation", "Ataxia", "Dependence"],
    interactions: ["CNS depressants", "Opioids"],
    lastRestocked: "2024-10-10",
    createdAt: "2024-03-25",
    updatedAt: "2024-10-10",
  },
  {
    id: "MED-013",
    name: "Ceftriaxone 1g",
    genericName: "Ceftriaxone Sodium",
    brandName: "Rocephin",
    category: "Antibiotics",
    form: "Injection",
    strength: "1g",
    unit: "vial",
    batchNumber: "BTH-2024-013",
    lotNumber: "LOT-CF012",
    quantity: 280,
    minStockLevel: 100,
    maxStockLevel: 600,
    reorderPoint: 150,
    expirationDate: "2026-02-28",
    manufacturer: "Roche",
    supplier: "Injectable Med Supply",
    unitPrice: 18.0,
    location: "Shelf F-1",
    barcode: "5901234123469",
    ndcCode: "0005-5466-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (15-25°C)",
    contraindications: [
      "Cephalosporin allergy",
      "Neonates with hyperbilirubinemia",
    ],
    sideEffects: ["Diarrhea", "Rash", "Injection site reactions"],
    interactions: ["Calcium-containing IV solutions"],
    lastRestocked: "2024-11-08",
    createdAt: "2024-05-05",
    updatedAt: "2024-11-08",
  },
  {
    id: "MED-014",
    name: "Gabapentin 300mg",
    genericName: "Gabapentin",
    brandName: "Neurontin",
    category: "Neurological",
    form: "Capsule",
    strength: "300mg",
    unit: "capsule",
    batchNumber: "BTH-2024-014",
    lotNumber: "LOT-GB345",
    quantity: 1200,
    minStockLevel: 400,
    maxStockLevel: 2500,
    reorderPoint: 600,
    expirationDate: "2026-08-10",
    manufacturer: "Pfizer Inc.",
    supplier: "NeuroMed Supply",
    unitPrice: 3.0,
    location: "Shelf E-1",
    barcode: "5901234123470",
    ndcCode: "0005-5467-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (25°C)",
    contraindications: ["Hypersensitivity"],
    sideEffects: ["Dizziness", "Somnolence", "Peripheral edema"],
    interactions: ["Antacids", "Morphine"],
    lastRestocked: "2024-11-14",
    createdAt: "2024-04-08",
    updatedAt: "2024-11-14",
  },
  {
    id: "MED-015",
    name: "Fluconazole 150mg",
    genericName: "Fluconazole",
    brandName: "Diflucan",
    category: "Antivirals",
    form: "Capsule",
    strength: "150mg",
    unit: "capsule",
    batchNumber: "BTH-2024-015",
    lotNumber: "LOT-FC678",
    quantity: 450,
    minStockLevel: 150,
    maxStockLevel: 800,
    reorderPoint: 225,
    expirationDate: "2026-04-25",
    manufacturer: "Pfizer Inc.",
    supplier: "AntifungalMed Supply",
    unitPrice: 6.5,
    location: "Shelf A-3",
    barcode: "5901234123471",
    ndcCode: "0005-5468-04",
    controlledSubstance: false,
    requiresRefrigeration: false,
    storageConditions: "Store at room temperature (25°C)",
    contraindications: ["QT prolongation", "Terfenadine use"],
    sideEffects: ["Headache", "Nausea", "Abdominal pain"],
    interactions: ["Warfarin", "Phenytoin", "Rifampin"],
    lastRestocked: "2024-10-25",
    createdAt: "2024-06-18",
    updatedAt: "2024-10-25",
  },
];

export const mockPatients: Patient[] = [
  {
    id: "PAT-001",
    mrn: "MRN-2024-00001",
    firstName: "สมชาย",
    lastName: "มีสุข",
    dateOfBirth: "1975-03-15",
    gender: "Male",
    allergies: ["Penicillin", "Sulfa drugs"],
    currentMedications: ["Metformin 500mg", "Lisinopril 10mg"],
    medicalConditions: ["Type 2 Diabetes", "Hypertension"],
    weight: 78,
    height: 172,
    bloodType: "A+",
    contactNumber: "081-234-5678",
    email: "somchai.m@email.com",
    insuranceProvider: "Thai Health Insurance",
    insuranceId: "THI-1234567",
    emergencyContact: {
      name: "สมหญิง มีสุข",
      relationship: "Spouse",
      phone: "081-234-5679",
    },
  },
  {
    id: "PAT-002",
    mrn: "MRN-2024-00002",
    firstName: "มาลี",
    lastName: "งามวงศ์",
    dateOfBirth: "1988-07-22",
    gender: "Female",
    allergies: [],
    currentMedications: ["Sertraline 50mg"],
    medicalConditions: ["Depression", "Anxiety"],
    weight: 55,
    height: 160,
    bloodType: "O+",
    contactNumber: "089-876-5432",
    email: "malee.n@email.com",
    insuranceProvider: "Bangkok Insurance",
    insuranceId: "BKI-9876543",
    emergencyContact: {
      name: "วิชัย งามวงศ์",
      relationship: "Father",
      phone: "089-876-5433",
    },
  },
  {
    id: "PAT-003",
    mrn: "MRN-2024-00003",
    firstName: "วิทยา",
    lastName: "พัฒนา",
    dateOfBirth: "1962-11-08",
    gender: "Male",
    allergies: ["Aspirin"],
    currentMedications: [
      "Atorvastatin 40mg",
      "Metoprolol 25mg",
      "Insulin Glargine",
    ],
    medicalConditions: [
      "Coronary Artery Disease",
      "Type 2 Diabetes",
      "Hyperlipidemia",
    ],
    weight: 82,
    height: 168,
    bloodType: "B+",
    contactNumber: "092-345-6789",
    email: "wittaya.p@email.com",
    insuranceProvider: "National Health Security",
    insuranceId: "NHS-5678901",
    emergencyContact: {
      name: "สุดา พัฒนา",
      relationship: "Spouse",
      phone: "092-345-6780",
    },
  },
  {
    id: "PAT-004",
    mrn: "MRN-2024-00004",
    firstName: "อรุณ",
    lastName: "สว่างจิต",
    dateOfBirth: "1995-02-28",
    gender: "Male",
    allergies: ["Codeine"],
    currentMedications: [],
    medicalConditions: ["Asthma"],
    weight: 70,
    height: 175,
    bloodType: "AB+",
    contactNumber: "095-678-1234",
    email: "arun.s@email.com",
    emergencyContact: {
      name: "พรทิพย์ สว่างจิต",
      relationship: "Mother",
      phone: "095-678-1235",
    },
  },
  {
    id: "PAT-005",
    mrn: "MRN-2024-00005",
    firstName: "นภา",
    lastName: "ใจดี",
    dateOfBirth: "1980-09-12",
    gender: "Female",
    allergies: ["Latex", "Ibuprofen"],
    currentMedications: ["Omeprazole 20mg", "Gabapentin 300mg"],
    medicalConditions: ["GERD", "Chronic Back Pain"],
    weight: 62,
    height: 158,
    bloodType: "O-",
    contactNumber: "086-123-4567",
    email: "napa.j@email.com",
    insuranceProvider: "AIA Thailand",
    insuranceId: "AIA-3456789",
    emergencyContact: {
      name: "สุริยา ใจดี",
      relationship: "Spouse",
      phone: "086-123-4568",
    },
  },
];

export const mockPrescriptions: Prescription[] = [
  {
    id: "RX-2024-001",
    patientId: "PAT-001",
    patientName: "สมชาย มีสุข",
    patientMRN: "MRN-2024-00001",
    physicianId: "PHY-001",
    physicianName: "Dr. สุรศักดิ์ รักษา",
    medicationId: "MED-002",
    medicationName: "Metformin 850mg",
    dosage: "850mg",
    frequency: "Twice daily",
    duration: "30 days",
    quantity: 60,
    refillsRemaining: 2,
    instructions: "Take with meals. Monitor blood glucose regularly.",
    status: "Pending",
    prescribedDate: "2024-12-03T09:30:00",
    priority: "Routine",
    notes: "Patient requested brand name medication",
  },
  {
    id: "RX-2024-002",
    patientId: "PAT-002",
    patientName: "มาลี งามวงศ์",
    patientMRN: "MRN-2024-00002",
    physicianId: "PHY-002",
    physicianName: "Dr. พิมพ์ใจ สุขใจ",
    medicationId: "MED-009",
    medicationName: "Sertraline 50mg",
    dosage: "50mg",
    frequency: "Once daily in morning",
    duration: "30 days",
    quantity: 30,
    refillsRemaining: 5,
    instructions: "Take in the morning with or without food. Avoid alcohol.",
    status: "Pending",
    prescribedDate: "2024-12-03T10:15:00",
    priority: "Routine",
  },
  {
    id: "RX-2024-003",
    patientId: "PAT-003",
    patientName: "วิทยา พัฒนา",
    patientMRN: "MRN-2024-00003",
    physicianId: "PHY-003",
    physicianName: "Dr. หทัยรัตน์ หัวใจแกร่ง",
    medicationId: "MED-005",
    medicationName: "Insulin Glargine 100U/mL",
    dosage: "20 units",
    frequency: "Once daily at bedtime",
    duration: "30 days",
    quantity: 1,
    refillsRemaining: 11,
    instructions: "Inject subcutaneously at bedtime. Rotate injection sites.",
    status: "Verified",
    prescribedDate: "2024-12-03T08:45:00",
    priority: "Urgent",
    notes: "Patient education on injection technique completed",
  },
  {
    id: "RX-2024-004",
    patientId: "PAT-004",
    patientName: "อรุณ สว่างจิต",
    patientMRN: "MRN-2024-00004",
    physicianId: "PHY-001",
    physicianName: "Dr. สุรศักดิ์ รักษา",
    medicationId: "MED-007",
    medicationName: "Albuterol Sulfate 90mcg/actuation",
    dosage: "2 puffs",
    frequency: "Every 4-6 hours as needed",
    duration: "30 days",
    quantity: 1,
    refillsRemaining: 3,
    instructions: "Shake well before each use. Wait 1 minute between puffs.",
    status: "Pending",
    prescribedDate: "2024-12-03T11:00:00",
    priority: "Urgent",
  },
  {
    id: "RX-2024-005",
    patientId: "PAT-005",
    patientName: "นภา ใจดี",
    patientMRN: "MRN-2024-00005",
    physicianId: "PHY-004",
    physicianName: "Dr. อนันต์ ปลอดภัย",
    medicationId: "MED-003",
    medicationName: "Morphine Sulfate 10mg",
    dosage: "10mg",
    frequency: "Every 4-6 hours as needed",
    duration: "7 days",
    quantity: 28,
    refillsRemaining: 0,
    instructions:
      "Take with food. Do not drive or operate machinery. Store securely.",
    status: "Pending",
    prescribedDate: "2024-12-03T14:30:00",
    priority: "STAT",
    notes: "Post-surgical pain management. Monitor for respiratory depression.",
  },
  {
    id: "RX-2024-006",
    patientId: "PAT-001",
    patientName: "สมชาย มีสุข",
    patientMRN: "MRN-2024-00001",
    physicianId: "PHY-001",
    physicianName: "Dr. สุรศักดิ์ รักษา",
    medicationId: "MED-004",
    medicationName: "Lisinopril 10mg",
    dosage: "10mg",
    frequency: "Once daily",
    duration: "30 days",
    quantity: 30,
    refillsRemaining: 5,
    instructions: "Take at the same time each day. Monitor blood pressure.",
    status: "Dispensed",
    prescribedDate: "2024-12-02T09:00:00",
    dispensedDate: "2024-12-02T14:30:00",
    dispensedBy: "นักเภสัช วิภา",
    priority: "Routine",
  },
];

export const mockPhysicians: Physician[] = [
  {
    id: "PHY-001",
    name: "Dr. สุรศักดิ์ รักษา",
    specialization: "Internal Medicine",
    licenseNumber: "MD-TH-12345",
    department: "Internal Medicine",
    email: "surasak.r@bjhhospital.com",
    phone: "02-123-4567",
    deaNumber: "DEA-12345",
  },
  {
    id: "PHY-002",
    name: "Dr. พิมพ์ใจ สุขใจ",
    specialization: "Psychiatry",
    licenseNumber: "MD-TH-23456",
    department: "Psychiatry",
    email: "pimjai.s@bjhhospital.com",
    phone: "02-123-4568",
    deaNumber: "DEA-23456",
  },
  {
    id: "PHY-003",
    name: "Dr. หทัยรัตน์ หัวใจแกร่ง",
    specialization: "Cardiology",
    licenseNumber: "MD-TH-34567",
    department: "Cardiology",
    email: "hatairat.h@bjhhospital.com",
    phone: "02-123-4569",
    deaNumber: "DEA-34567",
  },
  {
    id: "PHY-004",
    name: "Dr. อนันต์ ปลอดภัย",
    specialization: "Anesthesiology",
    licenseNumber: "MD-TH-45678",
    department: "Anesthesiology",
    email: "anan.p@bjhhospital.com",
    phone: "02-123-4570",
    deaNumber: "DEA-45678",
  },
];

export const mockStockAlerts: StockAlert[] = [
  {
    id: "ALERT-001",
    medicationId: "MED-002",
    medicationName: "Metformin 850mg",
    alertType: "Low Stock",
    severity: "High",
    currentQuantity: 180,
    threshold: 300,
    createdAt: "2024-12-03T06:00:00",
    acknowledged: false,
  },
  {
    id: "ALERT-002",
    medicationId: "MED-003",
    medicationName: "Morphine Sulfate 10mg",
    alertType: "Critical Stock",
    severity: "Critical",
    currentQuantity: 50,
    threshold: 100,
    createdAt: "2024-12-03T06:00:00",
    acknowledged: false,
  },
  {
    id: "ALERT-003",
    medicationId: "MED-007",
    medicationName: "Albuterol Sulfate 90mcg/actuation",
    alertType: "Low Stock",
    severity: "High",
    currentQuantity: 45,
    threshold: 100,
    createdAt: "2024-12-03T06:00:00",
    acknowledged: false,
  },
  {
    id: "ALERT-004",
    medicationId: "MED-012",
    medicationName: "Diazepam 5mg",
    alertType: "Critical Stock",
    severity: "Critical",
    currentQuantity: 25,
    threshold: 50,
    createdAt: "2024-12-03T06:00:00",
    acknowledged: false,
  },
  {
    id: "ALERT-005",
    medicationId: "MED-011",
    medicationName: "Epinephrine 1mg/mL",
    alertType: "Expiring",
    severity: "High",
    currentQuantity: 120,
    threshold: 50,
    expirationDate: "2025-01-15",
    createdAt: "2024-12-03T06:00:00",
    acknowledged: false,
  },
  {
    id: "ALERT-006",
    medicationId: "MED-005",
    medicationName: "Insulin Glargine 100U/mL",
    alertType: "Expiring",
    severity: "Medium",
    currentQuantity: 75,
    threshold: 50,
    expirationDate: "2025-02-28",
    createdAt: "2024-12-03T06:00:00",
    acknowledged: false,
  },
];

export const mockTransactions: InventoryTransaction[] = [
  {
    id: "TXN-001",
    medicationId: "MED-001",
    medicationName: "Amoxicillin 500mg",
    transactionType: "Dispensed",
    quantity: 30,
    previousQuantity: 2530,
    newQuantity: 2500,
    batchNumber: "BTH-2024-001",
    performedBy: "นักเภสัช วิภา",
    timestamp: "2024-12-03T14:30:00",
    notes: "Prescription RX-2024-007",
  },
  {
    id: "TXN-002",
    medicationId: "MED-004",
    medicationName: "Lisinopril 10mg",
    transactionType: "Dispensed",
    quantity: 30,
    previousQuantity: 1830,
    newQuantity: 1800,
    batchNumber: "BTH-2024-004",
    performedBy: "นักเภสัช วิภา",
    timestamp: "2024-12-02T14:30:00",
    notes: "Prescription RX-2024-006",
  },
  {
    id: "TXN-003",
    medicationId: "MED-006",
    medicationName: "Omeprazole 20mg",
    transactionType: "Received",
    quantity: 500,
    previousQuantity: 2700,
    newQuantity: 3200,
    batchNumber: "BTH-2024-006",
    performedBy: "พัสดุ สมบูรณ์",
    timestamp: "2024-12-01T10:00:00",
    notes: "Purchase order PO-2024-123",
  },
  {
    id: "TXN-004",
    medicationId: "MED-008",
    medicationName: "Atorvastatin 20mg",
    transactionType: "Adjusted",
    quantity: -50,
    previousQuantity: 2150,
    newQuantity: 2100,
    batchNumber: "BTH-2024-008",
    reason: "Inventory count correction",
    performedBy: "หัวหน้าเภสัช กาญจนา",
    timestamp: "2024-11-30T16:00:00",
    notes: "Physical count audit",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalMedications: 15,
  lowStockItems: 4,
  criticalStockItems: 2,
  expiringItems: 2,
  expiredItems: 0,
  pendingPrescriptions: 5,
  dispensedToday: 3,
  totalValue: 125450.5,
};

// Helper functions
export const getStockStatus = (medication: Medication): string => {
  const today = new Date();
  const expDate = new Date(medication.expirationDate);
  const daysUntilExpiry = Math.ceil(
    (expDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)
  );

  if (expDate < today) return "Expired";
  if (daysUntilExpiry <= 30) return "Expiring Soon";
  if (medication.quantity === 0) return "Out of Stock";
  if (medication.quantity <= medication.minStockLevel / 2) return "Critical";
  if (medication.quantity <= medication.minStockLevel) return "Low Stock";
  return "In Stock";
};

export const getStatusColor = (status: string): string => {
  switch (status) {
    case "In Stock":
      return "bg-emerald-100 text-emerald-800 border-emerald-200";
    case "Low Stock":
      return "bg-amber-100 text-amber-800 border-amber-200";
    case "Critical":
      return "bg-red-100 text-red-800 border-red-200";
    case "Out of Stock":
      return "bg-gray-100 text-gray-800 border-gray-200";
    case "Expired":
      return "bg-red-200 text-red-900 border-red-300";
    case "Expiring Soon":
      return "bg-orange-100 text-orange-800 border-orange-200";
    default:
      return "bg-gray-100 text-gray-800 border-gray-200";
  }
};

export const getPriorityColor = (priority: string): string => {
  switch (priority) {
    case "STAT":
      return "bg-red-500 text-white";
    case "Urgent":
      return "bg-amber-500 text-white";
    case "Routine":
      return "bg-blue-500 text-white";
    default:
      return "bg-gray-500 text-white";
  }
};

export const getPrescriptionStatusColor = (status: string): string => {
  switch (status) {
    case "Pending":
      return "bg-yellow-100 text-yellow-800 border-yellow-200";
    case "Verified":
      return "bg-blue-100 text-blue-800 border-blue-200";
    case "Dispensed":
      return "bg-emerald-100 text-emerald-800 border-emerald-200";
    case "Cancelled":
      return "bg-gray-100 text-gray-800 border-gray-200";
    case "On Hold":
      return "bg-orange-100 text-orange-800 border-orange-200";
    case "Partially Filled":
      return "bg-purple-100 text-purple-800 border-purple-200";
    default:
      return "bg-gray-100 text-gray-800 border-gray-200";
  }
};
